name: Deploy dev branch to dev repo

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Push to dev repository
      run: |
        git clone https://github.com/tanczikm/weboldalam-dev.git deploy-repo
        rm -rf deploy-repo/*
        cp -r * deploy-repo/
        cd deploy-repo
        git add .
        git commit -m "Auto-deploy from dev branch"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/tanczikm/weboldalam-dev.git main
