name: Deploy dev to weboldalam-dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone target repo
      run: |
        git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/tanczikm/weboldalam-dev.git deploy
        rsync -av --exclude=deploy --exclude='.git' ./ deploy/

    - name: Commit and Push to target
      run: |
        cd deploy
        git add .
        git commit -m "Automatikus deploy a dev branche-ből" || echo "Nincs változás"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/tanczikm/weboldalam-dev.git main
